In [20]:
import scipy
import matplotlib.pyplot as plt
import regex
import numpy as np
import random   # allows random number generation
random.seed(1234)

In [21]:
p = np.array([[  1,   0,   0,   0,   0],
              [1/3,   0, 2/3,   0,   0],
              [  0, 1/3,   0, 2/3,   0],
              [  0,   0, 1/3,   0, 2/3],
              [  0,   0,   0,   0,   1]])

In [ ]:
p_n = p

for i in range(0,3):
    p_n = np.matmul(p, p_n)
    # print(i+1)
    # print(p_n,'\n')

print(p_n)

[[1.         0.         0.         0.         0.        ]
 [0.40740741 0.09876543 0.         0.19753086 0.2962963 ]
 [0.16049383 0.         0.19753086 0.         0.64197531]
 [0.03703704 0.04938272 0.         0.09876543 0.81481481]
 [0.         0.         0.         0.         1.        ]]


In [23]:
print(np.matmul(np.matmul(p,p),np.matmul(p,p)))

[[1.         0.         0.         0.         0.        ]
 [0.40740741 0.09876543 0.         0.19753086 0.2962963 ]
 [0.16049383 0.         0.19753086 0.         0.64197531]
 [0.03703704 0.04938272 0.         0.09876543 0.81481481]
 [0.         0.         0.         0.         1.        ]]


In [19]:
p1 = np.matmul(p,p)
print(np.matmul(p1,p1))

[[1.         0.         0.         0.         0.        ]
 [0.80246914 0.19753086 0.         0.         0.        ]
 [0.40740741 0.39506173 0.19753086 0.         0.        ]
 [0.11111111 0.2962963  0.39506173 0.19753086 0.        ]
 [0.         0.         0.         0.         1.        ]]
