In [12]:
import scipy
import matplotlib.pyplot as plt
import regex
import numpy as np
from fractions import Fraction
import random   # allows random number generation
random.seed(1234)

In [31]:
20/41

0.4878048780487805

In [6]:
p = np.array([[9/10, 1/10, 0], [0, 7/8, 1/8], [2/5, 0, 3/5]])


In [7]:
print(p)

[[0.9   0.1   0.   ]
 [0.    0.875 0.125]
 [0.4   0.    0.6  ]]


In [28]:
p_n = p

for i in range(0,50):
    p_n = np.matmul(p, p_n)

print(p_n)

# for i in range(0,3):
#     print(p_n[i,0].as_integer_ratio(), p_n[i,1].as_integer_ratio(), p_n[i,2].as_integer_ratio())


[[0.48780487 0.3902439  0.12195122]
 [0.48780489 0.3902439  0.12195121]
 [0.48780486 0.39024391 0.12195123]]


In [30]:
p_k = p

for k in range(0,1000):
    p_k = np.matmul(p, p_k)


print(p_k)

[[0.48780488 0.3902439  0.12195122]
 [0.48780488 0.3902439  0.12195122]
 [0.48780488 0.3902439  0.12195122]]
